routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

load_route('installer');
load_route('website');

 Route::post('additional/services', 'ServiceController@getAdditionalServicesByServiceId')
 ->name('additional_services_by_service_id');

 Route::get('writer/apply', 'ApplicantController@create')
 ->name('writer_application_page');

 Route::post('writer/apply', 'ApplicantController@store')
 ->name('store_writer_application');


Auth::routes(['verify' => true]);

// Authenticated Users
Route::group(['middleware' => ['auth','verified'] ], function () {

    // Generic Routes (Admin and Staffs, both)
    load_route('generic');

    // For Admin Only
    Route::group(['middleware' => ['role:admin']], function () {
        load_route('admin');
        
    });
    // End of Admin only

    // For Staff Only
    Route::group(['middleware' => ['role:staff']], function () {        
        load_route('staff');
    });
    // End of Staff Only


    // Admin and staff
    Route::group(['middleware' => ['role:admin|staff']], function () {

        Route::get('tasks', 'TaskController@index')->name('tasks_list');
        Route::post('/tasks/datatable/', 'TaskController@datatable')->name('tasks_datatable');      
        Route::post('task/submit/{order}', 'TaskController@submit_work')->name('submit_work');
        Route::post('task/start/{order}', 'TaskController@start_working')->name('start_working');

    });
    // End of Admin and staff
  

});

app/User.php
<?php
namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use App\Traits\TagOperation;
use App\Traits\Wallet\HasWallet;
use App\Traits\Wallet\Transactionable;
use Spatie\Activitylog\Traits\CausesActivity; 
use Spatie\Permission\Models\Role;
use App\Setting;

class User extends Authenticatable implements MustVerifyEmail
{
    // use SoftDeletes;
    use Notifiable, HasRoles, TagOperation, HasWallet;
    use CausesActivity;
    use Transactionable;
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime'
    ];

    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function my_orders()
    {
        return $this->hasMany('App\Order', 'customer_id', 'id');
    }

    public function tasks()
    {
        return $this->hasMany('App\Order', 'staff_id', 'id');
    }

    public function ratings_received()
    {
        return $this->hasManyThrough('App\Rating', 'App\Order', 'staff_id');
    }

    public function unbilled_tasks()
    {
        return $this->tasks()
            ->where('order_status_id', ORDER_STATUS_COMPLETE)
            ->whereNull('billed');
    }

    public function bills()
    {
        return $this->hasMany('App\Bill');
    }

    public function pushNotification()
    {
        return $this->hasOne('App\PushNotification');
    }


    public function uncleared_payment_requests()
    {
        return $this->bills()->whereNull('paid');
    }

    public function uncleared_payment_total()
    {
        return $this->uncleared_payment_requests()
            ->get()
            ->sum('total');
    }

    public function records()
    {
        return $this->hasMany('App\UserRecord');
    }

    public function setMetaData()
    {
        $records = $this->records()->get();

        $this->meta = new \StdClass();

        if ($records->count() > 0) {
            foreach ($records as $row) {
                $this->meta->{$row->option_key} = $row->option_value;
            }
        }
    }

    public function meta($option_key)
    {
        $records = $this->records()
            ->where('option_key', $option_key)
            ->get();

        if ($records->count() > 0) {
            return optional($records->first())->option_value;
        }
    }

    public static function adminDropdown()
    {
        $data['tag_id_list'] = Tag::orderBy('name', 'ASC')->pluck('name', 'id')->toArray();

        $data['role_id_list'] = Role::orderBy('name', 'ASC')->pluck('name', 'name')->toArray();  

        $data['countries'] = ['' =>'Select'] + Country::orderBy('id', 'ASC')->pluck('name', 'name')->toArray();

        $data['referral_sources'] = ['' =>'Select'] + ReferralSource::orderBy('display_order', 'ASC')->pluck('name', 'name')->toArray();

        $data['timezones'] = Setting::get_list_of_time_zone();
        return $data;
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')
<div class="container page-container">
   <div class="row">
      <div class="col-md-12">
         <h4>Dashboard</h4>
         <hr>
      </div>
   </div>
   <div class="row">
      <div class="col-md-3">
         <div class="card card-bg-indigo">
            <div class="card-body">
               <h5 class="card-title">New Customers </h5>               
               <h5 class="float-right">
                  <i class="fas fa-spinner fa-spin"></i> 
                  <span id="users_count"></span>
               </h5>
               <p>Last 7 days</p>
            </div>
         </div>
      </div>
      <div class="col-md-3">
         <div class="card card-bg-indigo-light">
            <div class="card-body">
               <h5 class="card-title">Orders </h5>               
               <h5 class="float-right">
                  <i class="fas fa-spinner fa-spin"></i> 
                  <span id="orders_count"></span>
               </h5>
               <p>In progress</p>
            </div>
         </div>
      </div>
      <div class="col-md-3">
         <div class="card card-bg-red-light">
            <div class="card-body">
               <h5 class="card-title">Bill Paid</h5>
               <h5 class="float-right">
                  <i class="fas fa-spinner fa-spin"></i> 
                  <span id="paid_bills_amount"></span>
               </h5>
               <p>Last 30 days</p>
            </div>
         </div>
      </div>
      <div class="col-md-3">
         <div class="card card-bg-green">
            <div class="card-body">
               <h5 class="card-title">Profit</h5>
               <h5 class="float-right">
                  <i class="fas fa-spinner fa-spin"></i> 
                  <span id="profit_amount"></span>
               </h5>
               <p>Last 30 days</p>
            </div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-md-8">
         <canvas id="canvas"></canvas>
      </div>
      <div class="col-md-4">
         <div class="">
            <div class="">
               <h5 class="card-title">Activity Log</h5>
               <small>Most recent 5 activities <a href="{{ route('activity_log') }}">See All</a></small>
               @if($data['activities']->count() > 0)
                @foreach($data['activities'] as $activity)
                    @isset($activity->causer->id)
                    <p class="media">
                        <div class="media-body">
                        <a href="{{ route('user_profile', $activity->causer->id) }}">{{ $activity->causer->full_name }}</a> has
                        {!! $activity->description !!}
                        </div>
                        <small class="text-muted">
                            {{ $activity->created_at->format("d-M-Y H:i")  }}
                        </small>
                    </p>
                    @endisset
                @endforeach
               @else
                No activity
               @endif
            </div>
         </div>
      </div>
   </div>
</div>
@endsection
@push('scripts')

<script>

   window.chartColors = {
   red: 'rgb(255, 99, 132)',
   orange: 'rgb(255, 159, 64)',
   yellow: 'rgb(255, 205, 86)',
   green: 'rgb(75, 192, 192)',
   blue: 'rgb(54, 162, 235)',
   purple: 'rgb(153, 102, 255)',
   grey: 'rgb(201, 203, 207)'
};

// DEPRECATED
   window.randomScalingFactor = function() {
      return Math.floor(Math.random() * 100) + 20;
   };
      var formatted_values = [];
     
      var config = {
         type: 'line',
         data: {
            labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            datasets: [{
               label: 'Income',
               backgroundColor: window.chartColors.red,
               borderColor: window.chartColors.red,
               // backgroundColor: window.chartColors.blue,
               // borderColor: window.chartColors.blue,
               data: [
                  randomScalingFactor(),
                  randomScalingFactor(),
                  randomScalingFactor(),
                  randomScalingFactor(),
                  randomScalingFactor(),
                  randomScalingFactor(),
                  randomScalingFactor()
               ],
               fill: false,
            }]
         },
         options: {
            responsive: true,
            title: {
               display: true,
               text: 'Last 5 months'
            },
            tooltips: {
               mode: 'index',
               intersect: false,
            },
            hover: {
               mode: 'nearest',
               intersect: true
            },
            scales: {
               xAxes: [{
                  display: true,
                  scaleLabel: {
                     display: true,
                     labelString: 'Month'
                  }
               }],
               yAxes: [{
                  display: true,
                  scaleLabel: {
                     display: true,
                     labelString: 'Profit'
                  },
                  ticks: {
                    callback: function(label, index, labels) {
                        return accounting.formatNumber(label, currencyConfig.number);
                    }
                  }
               }]
            },
            tooltips: {
             callbacks: {
               label: function (tooltipItem, data) {
                 var label = data.datasets[tooltipItem.datasetIndex].label || ''

                 if (label) {
                   label += ': '
                 }    
                 label += accounting.formatMoney(tooltipItem.yLabel, currencyConfig.currency);
                 return label
               },
             },
           }
         }
      };

      window.onload = function() {         

         $.post( "{{ route('income_graph') }}", {
              '_token': $('meta[name=csrf-token]').attr('content'),              
          })
         .done(function(response) {
            config.data.labels = response.labels;
            config.data.datasets[0]['data'] = response.values;
            formatted_values = response.formatted_values; 
          
            var ctx = document.getElementById('canvas').getContext('2d');
            window.myLine = new Chart(ctx, config);         
         })
         .fail(function() {
             console.log( "error loading the chart" );
         });   
         
      };


      $(function(){

         fetch({name : 'users_count', 'elementId': 'users_count'});
         fetch({name : 'orders_count', 'elementId': 'orders_count'});
         fetch({name : 'paid_bills_amount', 'elementId': 'paid_bills_amount'});
         fetch({name : 'profit_amount', 'elementId': 'profit_amount'});


      });

      function fetch(query)
      {
        $.post( "{{ route('dashboard_statistics') }}", {
              '_token': "{{ csrf_token() }}",              
              'name': query.name
          })
         .done(function(response) {            
            $('#' + query.elementId).html(response).prev('.fa-spinner').hide();         
         })
         .fail(function() {
     
         });   
      }

   </script>
@endpush